### PR TITLE
Adding support for binaries (address #1)

### PR DESCRIPTION
**Pull request by wjzijderveld**
This is a hacked solution, but works :)

Just wanted to open the PR to discuss options.

Our use case is the following:
We use phpunit as a dev-dependency and use the executable provided to run it. 
At first I just ran the phpunit binary that gets installed by the root composer. That didn't work, as it then loads 2 autoloaders: the one from the root and the one from the component because we tell in phpunit.dist.xml to load the bootstrap, which loads the autoloader from the component.

**Undecided**
- [x] The target dir for the binaries (probably implement bin-dir like composer has?), as it now hardcodes to &lt;componentDir>/bin

### CODE REVIEW

**Comment by beberlei** [comment]
Great! Can we start with `vendor/bin` though? That is save directory to put stuff for now, and then yes we need "bin-dir" support.

**Comment by wjzijderveld** [comment]
Makes sense :)

But while making the adjustments I found an problem. With my current implementation it just happened to work by accident :-)

In the case of phpunit, it tries to load the autoload by looking in 3 locations: 
`array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php')`
This is a problem when we copy the executable to the `vendor/bin` directory, as it will never find the `autoload.php` When I symlink the file, I have the same problem I began with: it then tries to load the autoloader from the root package (as that is where to original executable is).

I'm not even sure this is easy to fix, as there is no way to tell how the executable tries to load files. It might try to use the autoloader, but it might also just try to include files relative from it's own location.

One thing that works with the autoloader, is to change the [`require` in `autoload_files.php`](https://github.com/composer/composer/blob/bc45d9185513575434021527d7756420e9f4b2cf/src/Composer/Autoload/AutoloadGenerator.php#L585) to `require_once`. But I doubt composer is willing to change that...

**Comment by wjzijderveld** [comment]
Just updated the PR.

- Adjusted the dumper to use require_once for files (no longer using the composerRequire function).
- I added a test for the autoloading part.
- Also needed to adjust a test to get them running. ([foo,bar] vs [bar,foo])

**Comment by wjzijderveld** [comment]
Found another edge-case yesterday. I'm not sure this is something Fiddler can and should account for, but for my case it's quit annoying :-)

I was trying to get phpspec working with our components and fiddler, but they [retrieve the autoloader pretty weird](https://github.com/phpspec/phpspec/blob/36c1e97d59630888fd022a542b1650ae5eab1f18/bin/phpspec#L6-L16):
- They first load the autoloader based on `getcwd()`
- After that (regardless if it succeeded or failed) it will load the autoloader based on __FILE__.

This would mean (when executed from the component), that it will first get the autoloader from the component. And after that it will load the autoloader from root. 
The autoloader from the root will then try to autoload files again, causing 'cannot redeclare' errors. 

When executed from the root it would mean the autoloader wouldn't know about the files from the component, so all tests fail :smile: 

Only solution I see now, is removing autoloading files from Fiddler all together, but allow for defining specific in the Fiddler.json, for cases where you do need it? Or if that turns out to be to invasive, maybe add an option to fiddler to skip autoloading files?

**Pull request merged**
